version: "3.9"

services:

  postgres:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: docker-demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
 
  backend:
    # build:
    #   context: ./backend
    image: naveenmanchanda/docker-demo-backend:1.0
    container_name: spring-backend
    ports:
      - "9012:9012"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/docker-demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

  frontend:
    # build:
    #   context: ./frontend
    image: naveenmanchanda/docker-demo-frontend:1.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
